# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-10-27 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='submission_votes',
            field=models.IntegerField(default=0),
        ),
    ]
